export { componentTemplate, componentTemplateRelations } from './componenttemplate'
export { propertyTemplate, propertyTemplateRelations } from './propertytemplate'
export { property, propertyRelations } from './property'
export { widget, widgetRelations } from './widgets'
export { componentsTags, componentsTagsRelations } from './componentstags'
export { controller, controllerRelations } from './controller'
export { screen, screenRelations } from './screen'
export { tag, tagRelations } from './tag'
export { dataType } from './datatype'
