/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ScreensImport } from './routes/screens'
import { Route as NoderedImport } from './routes/nodered'
import { Route as ControllersImport } from './routes/controllers'
import { Route as ConfigImport } from './routes/config'
import { Route as IndexImport } from './routes/index'
import { Route as ScreensIndexImport } from './routes/screens.index'
import { Route as ScreensScreenIdImport } from './routes/screens.$screenId'

// Create/Update Routes

const ScreensRoute = ScreensImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRoute,
} as any)

const NoderedRoute = NoderedImport.update({
  id: '/nodered',
  path: '/nodered',
  getParentRoute: () => rootRoute,
} as any)

const ControllersRoute = ControllersImport.update({
  id: '/controllers',
  path: '/controllers',
  getParentRoute: () => rootRoute,
} as any)

const ConfigRoute = ConfigImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ScreensIndexRoute = ScreensIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScreensRoute,
} as any)

const ScreensScreenIdRoute = ScreensScreenIdImport.update({
  id: '/$screenId',
  path: '/$screenId',
  getParentRoute: () => ScreensRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigImport
      parentRoute: typeof rootRoute
    }
    '/controllers': {
      id: '/controllers'
      path: '/controllers'
      fullPath: '/controllers'
      preLoaderRoute: typeof ControllersImport
      parentRoute: typeof rootRoute
    }
    '/nodered': {
      id: '/nodered'
      path: '/nodered'
      fullPath: '/nodered'
      preLoaderRoute: typeof NoderedImport
      parentRoute: typeof rootRoute
    }
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensImport
      parentRoute: typeof rootRoute
    }
    '/screens/$screenId': {
      id: '/screens/$screenId'
      path: '/$screenId'
      fullPath: '/screens/$screenId'
      preLoaderRoute: typeof ScreensScreenIdImport
      parentRoute: typeof ScreensImport
    }
    '/screens/': {
      id: '/screens/'
      path: '/'
      fullPath: '/screens/'
      preLoaderRoute: typeof ScreensIndexImport
      parentRoute: typeof ScreensImport
    }
  }
}

// Create and export the route tree

interface ScreensRouteChildren {
  ScreensScreenIdRoute: typeof ScreensScreenIdRoute
  ScreensIndexRoute: typeof ScreensIndexRoute
}

const ScreensRouteChildren: ScreensRouteChildren = {
  ScreensScreenIdRoute: ScreensScreenIdRoute,
  ScreensIndexRoute: ScreensIndexRoute,
}

const ScreensRouteWithChildren =
  ScreensRoute._addFileChildren(ScreensRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/controllers': typeof ControllersRoute
  '/nodered': typeof NoderedRoute
  '/screens': typeof ScreensRouteWithChildren
  '/screens/$screenId': typeof ScreensScreenIdRoute
  '/screens/': typeof ScreensIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/controllers': typeof ControllersRoute
  '/nodered': typeof NoderedRoute
  '/screens/$screenId': typeof ScreensScreenIdRoute
  '/screens': typeof ScreensIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/config': typeof ConfigRoute
  '/controllers': typeof ControllersRoute
  '/nodered': typeof NoderedRoute
  '/screens': typeof ScreensRouteWithChildren
  '/screens/$screenId': typeof ScreensScreenIdRoute
  '/screens/': typeof ScreensIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/config'
    | '/controllers'
    | '/nodered'
    | '/screens'
    | '/screens/$screenId'
    | '/screens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/config'
    | '/controllers'
    | '/nodered'
    | '/screens/$screenId'
    | '/screens'
  id:
    | '__root__'
    | '/'
    | '/config'
    | '/controllers'
    | '/nodered'
    | '/screens'
    | '/screens/$screenId'
    | '/screens/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRoute: typeof ConfigRoute
  ControllersRoute: typeof ControllersRoute
  NoderedRoute: typeof NoderedRoute
  ScreensRoute: typeof ScreensRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRoute: ConfigRoute,
  ControllersRoute: ControllersRoute,
  NoderedRoute: NoderedRoute,
  ScreensRoute: ScreensRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/config",
        "/controllers",
        "/nodered",
        "/screens"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/config": {
      "filePath": "config.tsx"
    },
    "/controllers": {
      "filePath": "controllers.tsx"
    },
    "/nodered": {
      "filePath": "nodered.tsx"
    },
    "/screens": {
      "filePath": "screens.tsx",
      "children": [
        "/screens/$screenId",
        "/screens/"
      ]
    },
    "/screens/$screenId": {
      "filePath": "screens.$screenId.tsx",
      "parent": "/screens"
    },
    "/screens/": {
      "filePath": "screens.index.tsx",
      "parent": "/screens"
    }
  }
}
ROUTE_MANIFEST_END */
